/* Project Euler: Problem 12: Highly divisible triangular number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:*/
function divisibleTriangleNumber(n) {
var trianglenumbers =[];
var number = []
var total = 0;
var count =0;
const max = Math.ceil(Math.sqrt(n));
for(var i = 1;i<=n;i++){
    number.push(i)
}
console.log(number);
   total = 0;
    for(var j = 1 ; j<= number.length;j++){
        total +=  j;
        trianglenumbers.push(total);
    }
    //console.log(total);
for(var k = 1; k<max;k++){
    for(var l = 0 ; l<trianglenumbers.length;l++){
        
    }
    
}
}
  
divisibleTriangleNumber(10);