/* Project Euler: Problem 12: Highly divisible triangular number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:*/
function divisibleTriangleNumber(n) {
var number = 0; 
var p = 1;
while(number === 0 ){
    count = 0;
    trinum = (p*(p+1))/2;
    //console.log(trinum);
    for(var i = 1;i<=Math.sqrt(trinum);i++){
        if(trinum % i === 0){
            count += 2;
        }
    }
    if(count>=n){
        number = trinum;
        break ;
    }
    p+=1;
//console.log(count,trinum,p);
}
console.log(number);
return number;
}
  
divisibleTriangleNumber(10);